---
- name: Remove Nginx
  hosts: web_servers
  tasks:
    - name: Stop Nginx service
      service:
        name: nginx
        state: stopped
        enabled: no

    - name: Remove Nginx package
      package:
        name: nginx
        state: absent

