---
- name: Install Nginx
  hosts: all
  become: yes
  tasks:
    - name: Install Nginx package
      package:
        name: nginx
        state: present

    - name: Ensure Nginx service is started
      service:
        name: nginx
        state: started
        enabled: yes

