---
- name: Remove Nginx
  hosts: all
  tasks:
    - name: Stop Nginx service
      service:
        name: nginx
        state: stopped
        enabled: no
        become: true

    - name: Remove Nginx package
      package:
        name: nginx
        state: absent
        become: true

